### ISSUE TITLE
Unknown config object 'gcode_macro'

### ISSUE THREAD

**Issue by GAZ082** [3DCoded/DynamicMacros#2]
```
[dynamicmacros]
configs: macros/standard_macros.cfg, macros/custom_macros.cfg # You can add more files to this list, separated by commas.
```

Hey there. Just changed that part in may config file and got that error upon restart. Tips? Thanks!

**Comment by 3DCoded** [comment]
Can you upload your `klippy.log` and your macros files? That way I can test on my setup and diagnose the problem.

**Comment by GAZ082** [comment]
[
[klippy (1).log](https://github.com/user-attachments/files/16384354/klippy.1.log)
](url)

[standard_macros.log](https://github.com/user-attachments/files/16384362/standard_macros.log)

The macros file I renamed it to .log so can be uploaded.

Thanks!

**Comment by 3DCoded** [comment]
From your log and config, it looks like Klipper is expecting at least one `gocde_macro`. Try configuring a blank `gcode_macro` before your `dynamicmacros` section, like this:
```
[gcode_macro blank]
gcode:
    RESPOND MSG="blank"
```

**Comment by 3DCoded** [comment]
You may also want to try moving the `dynamicmacros` section to after your `printer` and `mcu` sections.

**Comment by GAZ082** [comment]
Thanks. But now is complaining that PAUSE is alreade defined. Looked somewhere in my macros files and its just in one place.

**Comment by 3DCoded** [comment]
It looks like Klipper has certain macro names reserved for core functionality. I would advise against calling your macros:

- `PAUSE`
- `RESUME`
- `CANCEL_PRINT`
- `LOAD_FILAMENT`
- `UNLOAD_FILAMENT`

If you want to make them dynamic, you can have them call a dynamic macro (the following example is a standard macro):

```
[gcode_macro PAUSE]
gcode:
    DYNAMIC_PAUSE
```

I will add this to the documentation shortly.

**Comment by 3DCoded** [comment]
Also, when I try your config, my Klipper complains that the `PAUSE_BASE` command is already defined, not `PAUSE` itself. To fix it, I changed the `rename_existing` for each of the macros to:
- `PAUSE_BASE` -> `_PAUSE_BASE`
- `RESUME_BASE` -> `_RESUME_BASE`
- `CANCEL_PRINT_BASE` -> `_CANCEL_PRINT_BASE`

Then, I changed the names of the calls inside the macros themselves.

**Comment by 3DCoded** [comment]
Closing as it seems the original issue has been resolved. @GAZ082 If this issue still isn't resolved, please reopen this isssue.

**Comment by GAZ082** [comment]
@3DCoded didnt have time nor patience to try your solution, but now i want to improve my priming routine and will give this a shot again. Thanks!
